<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PeopleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => '1','user_id'=>'1', 'name' => 'احمد', 'last_name' => 'رضایی', 'father_name' => 'حسین', 'email' => 'ahmad.rezaei@example.com', 'phone' => '09121234567', 'tazkira_number' => '1234567890', 'actual_address' => 'تهران، خیابان ولیعصر', 'current_address' => 'تهران، میدان انقلاب', 'crime_case' => 'دزدی', 'ariza' => 'متهم به سرقت', 'subject_crim' => 'سرقت', 'crim_date' => '1403-05-01'],
            ['id' => '2','user_id'=>'1', 'name' => 'علی', 'last_name' => 'محمدی', 'father_name' => 'محمد', 'email' => 'ali.mohammadi@example.com', 'phone' => '09131234567', 'tazkira_number' => '2345678901', 'actual_address' => 'مشهد، خیابان امام رضا', 'current_address' => 'مشهد، میدان شهدا', 'crime_case' => 'جرم', 'ariza' => 'متهم به جرم', 'subject_crim' => 'جرم', 'crim_date' => '1403-06-15'],
            ['id' => '3','user_id'=>'1', 'name' => 'فاطمه', 'last_name' => 'احمدی', 'father_name' => 'سید', 'email' => 'fatemeh.ahmadi@example.com', 'phone' => '09132345678', 'tazkira_number' => '3456789012', 'actual_address' => 'شیراز، خیابان زند', 'current_address' => 'شیراز، میدان سعدی', 'crime_case' => 'قاچاق', 'ariza' => 'متهم به قاچاق', 'subject_crim' => 'قاچاق', 'crim_date' => '1403-07-10'],
            ['id' => '4','user_id'=>'1', 'name' => 'حسین', 'last_name' => 'کریمی', 'father_name' => 'حسن', 'email' => 'hossein.karimi@example.com', 'phone' => '09133456789', 'tazkira_number' => '4567890123', 'actual_address' => 'اصفهان، خیابان حافظ', 'current_address' => 'اصفهان، میدان انقلاب', 'crime_case' => 'تجاوز', 'ariza' => 'متهم به تجاوز', 'subject_crim' => 'تجاوز', 'crim_date' => '1403-08-20'],
            ['id' => '5','user_id'=>'1', 'name' => 'مریم', 'last_name' => 'سلیمی', 'father_name' => 'سلیمان', 'email' => 'maryam.solimi@example.com', 'phone' => '09134567890', 'tazkira_number' => '5678901234', 'actual_address' => 'کرج، خیابان آزادی', 'current_address' => 'کرج، میدان مادر', 'crime_case' => 'کلاهبرداری', 'ariza' => 'متهم به کلاهبرداری', 'subject_crim' => 'کلاهبرداری', 'crim_date' => '1403-09-05'],
            ['id' => '6','user_id'=>'1', 'name' => 'رضا', 'last_name' => 'علیزاده', 'father_name' => 'علی', 'email' => 'reza.alizadeh@example.com', 'phone' => '09135678901', 'tazkira_number' => '6789012345', 'actual_address' => 'تبریز، خیابان استاد شهریار', 'current_address' => 'تبریز، میدان بسیج', 'crime_case' => 'سرقت', 'ariza' => 'متهم به سرقت', 'subject_crim' => 'سرقت', 'crim_date' => '1403-10-15'],
            ['id' => '7','user_id'=>'1', 'name' => 'سارا', 'last_name' => 'محمدی', 'father_name' => 'محمد', 'email' => 'sara.mohammadi@example.com', 'phone' => '09136789012', 'tazkira_number' => '7890123456', 'actual_address' => 'تهران، خیابان فرشته', 'current_address' => 'تهران، میدان ونک', 'crime_case' => 'تجاوز', 'ariza' => 'متهم به تجاوز', 'subject_crim' => 'تجاوز', 'crim_date' => '1403-11-25'],
            ['id' => '8', 'user_id' => 1, 'name' => 'بهرام', 'last_name' => 'کریمی', 'father_name' => 'رضا', 'email' => 'bahram.karimi@example.com', 'phone' => '09181234567', 'tazkira_number' => '3456789012', 'actual_address' => 'کرج، خیابان شهیدان', 'current_address' => 'کرج، میدان ولیعصر', 'crime_case' => 'قتل', 'ariza' => 'متهم به قتل', 'subject_crim' => 'قتل', 'crim_date' => '1403-07-22'],
            ['id' => '9', 'user_id' => 1, 'name' => 'مهناز', 'last_name' => 'رحیمی', 'father_name' => 'سعید', 'email' => 'mahnaz.rahimi@example.com', 'phone' => '09191234567', 'tazkira_number' => '4567890123', 'actual_address' => 'اصفهان، خیابان آزادی', 'current_address' => 'اصفهان، میدان امام', 'crime_case' => 'کلاهبرداری', 'ariza' => 'متهم به کلاهبرداری', 'subject_crim' => 'کلاهبرداری', 'crim_date' => '1403-08-10'],
            ['id' => '10', 'user_id' => 1, 'name' => 'مهدی', 'last_name' => 'علیزاده', 'father_name' => 'حسین', 'email' => 'mehdi.alizadeh@example.com', 'phone' => '09201234567', 'tazkira_number' => '5678901234', 'actual_address' => 'تبریز، خیابان آزادی', 'current_address' => 'تبریز، میدان جمهوری', 'crime_case' => 'ضرب و شتم', 'ariza' => 'متهم به ضرب و شتم', 'subject_crim' => 'ضرب و شتم', 'crim_date' => '1403-09-05'],
            ['id' => '11', 'user_id' => 1, 'name' => 'سارا', 'last_name' => 'فریدی', 'father_name' => 'امیر', 'email' => 'sara.feydi@example.com', 'phone' => '09301234567', 'tazkira_number' => '6789012345', 'actual_address' => 'شیراز، خیابان امام خمینی', 'current_address' => 'شیراز، میدان انقلاب', 'crime_case' => 'مواد مخدر', 'ariza' => 'متهم به مواد مخدر', 'subject_crim' => 'مواد مخدر', 'crim_date' => '1403-10-20'],
            ['id' => '12', 'user_id' => 1, 'name' => 'سعید', 'last_name' => 'اکبری', 'father_name' => 'مرتضی', 'email' => 'saeed.akbari@example.com', 'phone' => '09311234567', 'tazkira_number' => '7890123456', 'actual_address' => 'قزوین، خیابان آیت‌الله طالقانی', 'current_address' => 'قزوین، میدان قدس', 'crime_case' => 'سرقت مسلحانه', 'ariza' => 'متهم به سرقت مسلحانه', 'subject_crim' => 'سرقت مسلحانه', 'crim_date' => '1403-11-15'],
            ['id' => '13', 'user_id' => 1, 'name' => 'رضا', 'last_name' => 'خدابخشی', 'father_name' => 'جواد', 'email' => 'reza.khodaybakhshi@example.com', 'phone' => '09321234567', 'tazkira_number' => '8901234567', 'actual_address' => 'رشت، خیابان سردار جنگل', 'current_address' => 'رشت، میدان شهید بهشتی', 'crime_case' => 'تجاوز', 'ariza' => 'متهم به تجاوز', 'subject_crim' => 'تجاوز', 'crim_date' => '1403-12-05'],
            ['id' => '14', 'user_id' => 1, 'name' => 'ندا', 'last_name' => 'آقاخانی', 'father_name' => 'حمید', 'email' => 'neda.aghakhani@example.com', 'phone' => '09331234567', 'tazkira_number' => '9012345678', 'actual_address' => 'یزد، خیابان امام', 'current_address' => 'یزد، میدان آزادی', 'crime_case' => 'آتش‌سوزی', 'ariza' => 'متهم به آتش‌سوزی', 'subject_crim' => 'آتش‌سوزی', 'crim_date' => '1404-01-01'],
            ['id' => '15', 'user_id' => 1, 'name' => 'امیر', 'last_name' => 'عزیزی', 'father_name' => 'هادی', 'email' => 'amir.azizi@example.com', 'phone' => '09341234567', 'tazkira_number' => '0123456789', 'actual_address' => 'کرمان، خیابان گلزار', 'current_address' => 'کرمان، میدان امام حسین', 'crime_case' => 'تجاوز جنسی', 'ariza' => 'متهم به تجاوز جنسی', 'subject_crim' => 'تجاوز جنسی', 'crim_date' => '1404-02-20'],
            ['id' => '16', 'user_id' => 1, 'name' => 'الهام', 'last_name' => 'قاسمی', 'father_name' => 'پیمان', 'email' => 'elham.qasemi@example.com', 'phone' => '09351234567', 'tazkira_number' => '1234567891', 'actual_address' => 'خرم‌آباد، خیابان آزادی', 'current_address' => 'خرم‌آباد، میدان ولیعصر', 'crime_case' => 'اخلال در نظم', 'ariza' => 'متهم به اخلال در نظم', 'subject_crim' => 'اخلال در نظم', 'crim_date' => '1404-03-15'],
            ['id' => '17', 'user_id' => 1, 'name' => 'فاطمه', 'last_name' => 'محمدی', 'father_name' => 'حسین', 'email' => 'fatemeh.mohammadi@example.com', 'phone' => '09361234567', 'tazkira_number' => '2345678902', 'actual_address' => 'سنندج، خیابان سعدی', 'current_address' => 'سنندج، میدان انقلاب', 'crime_case' => 'دزدی', 'ariza' => 'متهم به دزدی', 'subject_crim' => 'دزدی', 'crim_date' => '1404-04-01'],
            ['id' => '18', 'user_id' => 1, 'name' => 'مهدیه', 'last_name' => 'احمدی', 'father_name' => 'احمد', 'email' => 'mahdieh.ahmadi@example.com', 'phone' => '09371234567', 'tazkira_number' => '3456789013', 'actual_address' => 'همدان، خیابان شریعتی', 'current_address' => 'همدان، میدان آزادی', 'crime_case' => 'قاچاق', 'ariza' => 'متهم به قاچاق', 'subject_crim' => 'قاچاق', 'crim_date' => '1404-05-10'],
            ['id' => '19', 'user_id' => 1, 'name' => 'حسین', 'last_name' => 'احمدی', 'father_name' => 'جواد', 'email' => 'hosein.ahmadi@example.com', 'phone' => '09381234567', 'tazkira_number' => '4567890124', 'actual_address' => 'بندرعباس، خیابان خلیج فارس', 'current_address' => 'بندرعباس، میدان امام', 'crime_case' => 'دزدی', 'ariza' => 'متهم به دزدی', 'subject_crim' => 'دزدی', 'crim_date' => '1404-06-20'],
        ];
        DB::table('people')->insert($data);
    }
}
